
export type DayOfWeek = 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday';

export interface ClassTemplate {
  id: string;
  name: string;
  teacher: string;
  itemsToBring: string[];
}

export interface ClassSchedule {
  id: string;
  templateId: string;
  startTime: string;
  endTime: string;
  dayOfWeek: DayOfWeek;
}

export interface Kid {
  id: string;
  name: string;
  age: number;
  grade: string;
  schedule: ClassSchedule[];
}

export interface AppData {
  kids: Kid[];
  templates: ClassTemplate[];
  imageMap: Record<string, string>;
  language: string;
}

export type AppView = 'home' | 'admin' | 'kid-detail';

export const LANGUAGES = [
  { code: 'en', name: 'English', dir: 'ltr' },
  { code: 'he', name: 'עברית (Hebrew)', dir: 'rtl' },
  { code: 'ar', name: 'العربية (Arabic)', dir: 'rtl' },
  { code: 'es', name: 'Español', dir: 'ltr' },
  { code: 'fr', name: 'Français', dir: 'ltr' },
  { code: 'de', name: 'Deutsch', dir: 'ltr' },
  { code: 'zh', name: '中文', dir: 'ltr' },
  { code: 'ja', name: '日本語', dir: 'ltr' },
];

export const TRANSLATIONS: Record<string, any> = {
  en: {
    appName: 'School Buddy',
    goodMorning: 'Good morning!',
    todayIs: "Today is {day}",
    classesToday: '{count} classes today',
    nothingNeeded: 'Nothing needed',
    requiredFor: 'Required for {day}',
    todaysBag: "Today's Bag",
    weeklyPlanner: 'Weekly Planner',
    today: 'Today',
    week: 'Week',
    addClass: '+ Class',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    kids: 'Kids',
    templates: 'Library',
    debug: 'Vault',
    language: 'Lang',
    new: '+ New',
    kidProfiles: 'Profiles',
    classTemplates: 'Classes',
    name: 'Name',
    age: 'Age',
    grade: 'Grade',
    teacher: 'Teacher',
    items: 'Items',
    update: 'Update',
    chooseClass: 'Select Class',
    startTime: 'Start',
    endTime: 'End',
    timeOrderError: 'End must be after start',
    home: 'Home',
    settings: 'Settings',
    addFirst: 'Add Your First Kid',
    welcome: 'Welcome to School Buddy',
    welcomeSub: "Let's get started by adding your kids.",
    noClasses: 'No classes scheduled',
    systemVault: 'System Vault',
    systemVaultSub: 'Export or restore your profile data here.',
    restoreBtn: 'Perform Restoration',
    backupPlaceholder: 'Paste system backup string...',
    classNamePlaceholder: 'e.g. Biology, Art...',
    teacherPlaceholder: 'Instructor name',
    itemsPlaceholder: 'Notebook, Pen, Calculator...',
    namePlaceholder: 'e.g. Leo Smith',
    agePlaceholder: 'Years',
    gradePlaceholder: 'Level',
    visualizing: 'Visualizing items...',
    createProfile: 'Create New Profile',
    configureClass: 'Configure Class',
    managed: 'Managed',
    saved: 'Saved',
    days: {
      Sunday: 'Sunday',
      Monday: 'Monday',
      Tuesday: 'Tuesday',
      Wednesday: 'Wednesday',
      Thursday: 'Thursday',
      Friday: 'Friday'
    }
  },
  he: {
    appName: 'לו״ז הילדים',
    goodMorning: 'בוקר טוב!',
    todayIs: 'היום {day}',
    classesToday: '{count} שיעורים היום',
    nothingNeeded: 'לא צריך כלום',
    requiredFor: 'נדרש ליום {day}',
    todaysBag: 'התיק להיום',
    weeklyPlanner: 'תכנון שבועי',
    today: 'היום',
    week: 'שבוע',
    addClass: '+ שיעור',
    edit: 'עריכה',
    save: 'שמירה',
    cancel: 'ביטול',
    kids: 'ילדים',
    templates: 'ספריה',
    debug: 'כספת',
    language: 'שפה',
    new: '+ חדש',
    kidProfiles: 'פרופילים',
    classTemplates: 'שיעורים',
    name: 'שם',
    age: 'גיל',
    grade: 'כיתה',
    teacher: 'מורה',
    items: 'פריטים',
    update: 'עדכון',
    chooseClass: 'בחר שיעור',
    startTime: 'התחלה',
    endTime: 'סיום',
    timeOrderError: 'זמן הסיום חייב להיות אחרי ההתחלה',
    home: 'בית',
    settings: 'הגדרות',
    addFirst: 'הוסף את הילד הראשון',
    welcome: 'ברוכים הבאים ללו״ז הילדים',
    welcomeSub: 'בואו נתחיל על ידי הוספת הילדים.',
    noClasses: 'אין שיעורים מתוכננים',
    systemVault: 'כספת מערכת',
    systemVaultSub: 'ייצוא או שחזור נתוני הפרופיל שלך כאן.',
    restoreBtn: 'בצע שחזור',
    backupPlaceholder: 'הדבק מחרוזת גיבוי...',
    classNamePlaceholder: 'למשל: ביולוגיה, אמנות...',
    teacherPlaceholder: 'שם המורה',
    itemsPlaceholder: 'מחברת, עט, מחשבון...',
    namePlaceholder: 'למשל: ליאו לוי',
    agePlaceholder: 'שנים',
    gradePlaceholder: 'דרגה/כיתה',
    visualizing: 'יוצר תמונות לפריטים...',
    createProfile: 'צור פרופיל חדש',
    configureClass: 'הגדר שיעור',
    managed: 'מנוהלים',
    saved: 'שמורים',
    days: {
      Sunday: 'יום ראשון',
      Monday: 'יום שני',
      Tuesday: 'יום שלישי',
      Wednesday: 'יום רביעי',
      Thursday: 'יום חמישי',
      Friday: 'יום שישי'
    }
  },
  ar: {
    appName: 'مساعد المدرسة',
    goodMorning: 'صباح الخير!',
    todayIs: 'اليوم هو {day}',
    classesToday: '{count} حصص اليوم',
    nothingNeeded: 'لا شيء مطلوب',
    requiredFor: 'مطلوب ليوم {day}',
    todaysBag: 'حقيبة اليوم',
    weeklyPlanner: 'المخطط الأسبوعي',
    today: 'اليوم',
    week: 'الأسبوع',
    addClass: '+ حصة',
    edit: 'تعديل',
    save: 'حفظ',
    cancel: 'إلغاء',
    kids: 'أطفال',
    templates: 'مكتبة',
    debug: 'خزنة',
    language: 'لغة',
    new: '+ جديد',
    kidProfiles: 'ملفات',
    classTemplates: 'حصص',
    name: 'الاسم',
    age: 'العمر',
    grade: 'الصف',
    teacher: 'المعلم',
    items: 'أغراض',
    update: 'تحديث',
    chooseClass: 'اختر الحصة',
    startTime: 'البداية',
    endTime: 'النهاية',
    timeOrderError: 'النهاية بعد البداية',
    home: 'الرئيسية',
    settings: 'الإعدادات',
    addFirst: 'أضف طفلك الأول',
    welcome: 'مرحباً في مساعد المدرسة',
    welcomeSub: 'لنبدأ بإضافة أطفالك.',
    noClasses: 'لا توجد حصص مجدولة',
    systemVault: 'خزنة النظام',
    systemVaultSub: 'تصدير أو استعادة البيانات هنا.',
    restoreBtn: 'تنفيذ الاستعادة',
    backupPlaceholder: 'الصق نص النسخة الاحتياطية...',
    classNamePlaceholder: 'مثلاً: أحياء، فن...',
    teacherPlaceholder: 'اسم المعلم',
    itemsPlaceholder: 'دفتر، قلم، حاسبة...',
    namePlaceholder: 'مثلاً: ليو سميث',
    agePlaceholder: 'سنوات',
    gradePlaceholder: 'المستوى',
    visualizing: 'جاري إنشاء الصور...',
    createProfile: 'إنشاء ملف جديد',
    configureClass: 'تكوين الحصة',
    managed: 'مُدار',
    saved: 'محفوظ',
    days: {
      Sunday: 'الأحد',
      Monday: 'الاثنين',
      Tuesday: 'الثلاثاء',
      Wednesday: 'الأربعاء',
      Thursday: 'الخميس',
      Friday: 'الجمعة'
    }
  },
  es: {
    appName: 'Compañero Escolar',
    goodMorning: '¡Buen día!',
    todayIs: 'Hoy es {day}',
    classesToday: '{count} clases hoy',
    nothingNeeded: 'Nada necesario',
    requiredFor: 'Requerido para el {day}',
    todaysBag: 'Mochila de Hoy',
    weeklyPlanner: 'Plan Semanal',
    today: 'Hoy',
    week: 'Semana',
    addClass: '+ Clase',
    edit: 'Editar',
    save: 'Guardar',
    cancel: 'Cancelar',
    kids: 'Niños',
    templates: 'Librería',
    debug: 'Bóveda',
    language: 'Idioma',
    new: '+ Nuevo',
    kidProfiles: 'Perfiles',
    classTemplates: 'Clases',
    name: 'Nombre',
    age: 'Edad',
    grade: 'Grado',
    teacher: 'Profesor',
    items: 'Artículos',
    update: 'Actualizar',
    chooseClass: 'Seleccionar',
    startTime: 'Inicio',
    endTime: 'Fin',
    timeOrderError: 'El fin debe ser después del inicio',
    home: 'Inicio',
    settings: 'Ajustes',
    addFirst: 'Añade a tu primer hijo',
    welcome: 'Bienvenido',
    welcomeSub: 'Empecemos añadiendo a tus hijos.',
    noClasses: 'No hay clases programadas',
    systemVault: 'Bóveda del Sistema',
    systemVaultSub: 'Exporta o restaura tus datos aquí.',
    restoreBtn: 'Realizar Restauración',
    backupPlaceholder: 'Pega la cadena de respaldo...',
    classNamePlaceholder: 'ej. Biología, Arte...',
    teacherPlaceholder: 'Nombre del instructor',
    itemsPlaceholder: 'Cuaderno, Lápiz, Calculadora...',
    namePlaceholder: 'ej. Leo Smith',
    agePlaceholder: 'Años',
    gradePlaceholder: 'Nivel',
    visualizing: 'Visualizando artículos...',
    createProfile: 'Crear Nuevo Perfil',
    configureClass: 'Configurar Clase',
    managed: 'Gestionados',
    saved: 'Guardados',
    days: {
      Sunday: 'Domingo',
      Monday: 'Lunes',
      Tuesday: 'Martes',
      Wednesday: 'Miércoles',
      Thursday: 'Jueves',
      Friday: 'Viernes'
    }
  },
  fr: {
    appName: 'Compagnon École',
    goodMorning: 'Bonjour !',
    todayIs: 'C’est {day}',
    classesToday: '{count} cours aujourd’hui',
    nothingNeeded: 'Rien à prévoir',
    requiredFor: 'Requis pour {day}',
    todaysBag: 'Sac d’aujourd’hui',
    weeklyPlanner: 'Planning Hebdo',
    today: 'Aujourd’hui',
    week: 'Semaine',
    addClass: '+ Cours',
    edit: 'Modifier',
    save: 'Sauver',
    cancel: 'Annuler',
    kids: 'Enfants',
    templates: 'Biblio',
    debug: 'Coffre',
    language: 'Langue',
    new: '+ Nouveau',
    kidProfiles: 'Profils',
    classTemplates: 'Cours',
    name: 'Nom',
    age: 'Âge',
    grade: 'Classe',
    teacher: 'Prof',
    items: 'Objets',
    update: 'Mise à jour',
    chooseClass: 'Choisir cours',
    startTime: 'Début',
    endTime: 'Fin',
    timeOrderError: 'La fin doit être après le début',
    home: 'Accueil',
    settings: 'Réglages',
    addFirst: 'Ajouter un enfant',
    welcome: 'Bienvenue',
    welcomeSub: 'Commencez par ajouter vos enfants.',
    noClasses: 'Aucun cours prévu',
    systemVault: 'Coffre Système',
    systemVaultSub: 'Exportez ou restaurez vos données ici.',
    restoreBtn: 'Restaurer',
    backupPlaceholder: 'Collez la sauvegarde...',
    classNamePlaceholder: 'ex: Biologie, Art...',
    teacherPlaceholder: 'Nom du prof',
    itemsPlaceholder: 'Cahier, Stylo, Calculatrice...',
    namePlaceholder: 'ex: Léo Smith',
    agePlaceholder: 'Ans',
    gradePlaceholder: 'Niveau',
    visualizing: 'Génération d’images...',
    createProfile: 'Créer un Profil',
    configureClass: 'Configurer le Cours',
    managed: 'Gérés',
    saved: 'Sauvegardés',
    days: {
      Sunday: 'Dimanche',
      Monday: 'Lundi',
      Tuesday: 'Mardi',
      Wednesday: 'Mercredi',
      Thursday: 'Jeudi',
      Friday: 'Vendredi'
    }
  },
  de: {
    appName: 'Schul-Buddy',
    goodMorning: 'Guten Morgen!',
    todayIs: 'Heute ist {day}',
    classesToday: '{count} Stunden heute',
    nothingNeeded: 'Nichts benötigt',
    requiredFor: 'Nötig für {day}',
    todaysBag: 'Heutige Tasche',
    weeklyPlanner: 'Wochenplan',
    today: 'Heute',
    week: 'Woche',
    addClass: '+ Fach',
    edit: 'Bearbeiten',
    save: 'Speichern',
    cancel: 'Abbrechen',
    kids: 'Kinder',
    templates: 'Bibliothek',
    debug: 'Tresor',
    language: 'Sprache',
    new: '+ Neu',
    kidProfiles: 'Profile',
    classTemplates: 'Fächer',
    name: 'Name',
    age: 'Alter',
    grade: 'Klasse',
    teacher: 'Lehrer',
    items: 'Dinge',
    update: 'Update',
    chooseClass: 'Fach wählen',
    startTime: 'Beginn',
    endTime: 'Ende',
    timeOrderError: 'Ende muss nach Beginn liegen',
    home: 'Home',
    settings: 'Optionen',
    addFirst: 'Erstes Kind hinzufügen',
    welcome: 'Willkommen',
    welcomeSub: 'Fügen Sie Ihre Kinder hinzu.',
    noClasses: 'Keine Stunden geplant',
    systemVault: 'Systemtresor',
    systemVaultSub: 'Export oder Wiederherstellung hier.',
    restoreBtn: 'Wiederherstellen',
    backupPlaceholder: 'Backup-Code hier einfügen...',
    classNamePlaceholder: 'z.B. Biologie, Kunst...',
    teacherPlaceholder: 'Name des Lehrers',
    itemsPlaceholder: 'Heft, Stift, Rechner...',
    namePlaceholder: 'z.B. Leo Schmidt',
    agePlaceholder: 'Jahre',
    gradePlaceholder: 'Stufe',
    visualizing: 'Bilder werden generiert...',
    createProfile: 'Profil erstellen',
    configureClass: 'Fach konfigurieren',
    managed: 'Verwaltet',
    saved: 'Gespeichert',
    days: {
      Sunday: 'Sonntag',
      Monday: 'Montag',
      Tuesday: 'Dienstag',
      Wednesday: 'Mittwoch',
      Thursday: 'Donnerstag',
      Friday: 'Freitag'
    }
  },
  zh: {
    appName: '学校助手',
    goodMorning: '早上好！',
    todayIs: '今天是 {day}',
    classesToday: '今天有 {count} 节课',
    nothingNeeded: '无需带任何东西',
    requiredFor: '{day} 需要准备',
    todaysBag: '今日书包',
    weeklyPlanner: '每周计划',
    today: '今日',
    week: '每周',
    addClass: '+ 课程',
    edit: '编辑',
    save: '保存',
    cancel: '取消',
    kids: '孩子',
    templates: '库',
    debug: '存储',
    language: '语言',
    new: '+ 新建',
    kidProfiles: '个人资料',
    classTemplates: '课程',
    name: '名字',
    age: '年龄',
    grade: '年级',
    teacher: '老师',
    items: '物品',
    update: '更新',
    chooseClass: '选择课程',
    startTime: '开始',
    endTime: '结束',
    timeOrderError: '结束时间必须晚于开始时间',
    home: '首页',
    settings: '设置',
    addFirst: '添加第一个孩子',
    welcome: '欢迎',
    welcomeSub: '请先添加您的孩子。',
    noClasses: '暂无课程安排',
    systemVault: '系统保险箱',
    systemVaultSub: '在此导出或恢复您的数据。',
    restoreBtn: '执行恢复',
    backupPlaceholder: '在此粘贴备份字符串...',
    classNamePlaceholder: '例如：生物、美术...',
    teacherPlaceholder: '老师姓名',
    itemsPlaceholder: '笔记本、笔、计算器...',
    namePlaceholder: '例如：李小明',
    agePlaceholder: '岁',
    gradePlaceholder: '年级',
    visualizing: '正在生成物品图片...',
    createProfile: '创建新资料',
    configureClass: '配置课程',
    managed: '已管理',
    saved: '已保存',
    days: {
      Sunday: '星期日',
      Monday: '星期一',
      Tuesday: '星期二',
      Wednesday: '星期三',
      Thursday: '星期四',
      Friday: '星期五'
    }
  },
  ja: {
    appName: 'スクールバディ',
    goodMorning: 'おはようございます！',
    todayIs: '今日は {day}',
    classesToday: '今日は {count} つの授業',
    nothingNeeded: '持ち物なし',
    requiredFor: '{day} の持ち物',
    todaysBag: '今日の持ち物',
    weeklyPlanner: '週間プラン',
    today: '今日',
    week: '週間',
    addClass: '+ 授業',
    edit: '編集',
    save: '保存',
    cancel: 'キャンセル',
    kids: '子供',
    templates: 'ライブラリ',
    debug: '保管庫',
    language: '言語',
    new: '+ 新規',
    kidProfiles: 'プロファイル',
    classTemplates: '授業',
    name: '名前',
    age: '年齢',
    grade: '学年',
    teacher: '先生',
    items: '持ち物',
    update: '更新',
    chooseClass: '授業を選択',
    startTime: '開始',
    endTime: '終了',
    timeOrderError: '終了時間は開始時間より後である必要があります',
    home: 'ホーム',
    settings: '設定',
    addFirst: '最初の子供を追加',
    welcome: 'ようこそ',
    welcomeSub: '子供を追加して始めましょう。',
    noClasses: '授業の予定はありません',
    systemVault: 'システム保管庫',
    systemVaultSub: 'データの書き出し・復元ができます。',
    restoreBtn: '復元を実行',
    backupPlaceholder: 'バックアップ文字列を貼り付け...',
    classNamePlaceholder: '例：生物、美術...',
    teacherPlaceholder: '先生の名前',
    itemsPlaceholder: 'ノート、ペン、電卓...',
    namePlaceholder: '例：山田太郎',
    agePlaceholder: '歳',
    gradePlaceholder: '学年',
    visualizing: '画像を生成中...',
    createProfile: 'プロフィール作成',
    configureClass: '授業の設定',
    managed: '管理中',
    saved: '保存済み',
    days: {
      Sunday: '日曜日',
      Monday: '月曜日',
      Tuesday: '火曜日',
      Wednesday: '水曜日',
      Thursday: '木曜日',
      Friday: '金曜日'
    }
  }
};
